spring:
  application:
    name: shipping-service
  datasource:
    url: jdbc:postgresql://localhost:5444/shipping
    username: shipping
    password: shipping
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

server:
  port: 8084
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

idempiere:
  events:
    shipments-topic: shipments.events
    orders-topic: orders.events

logging:
  level:
    root: INFO
    com.corestory.idempiere: DEBUG
